config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"

    post "/signup", to: "users#create"
    get "/signup", to: "users#new"

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save :downcase_email
  VALID_EMAIL_REGEX = Settings.validates.regex.email
  validates :name, presence: true,
            length: {maximum: Settings.validates.length.name_max}
  validates :email, presence: true,
            length: {maximum: Settings.validates.length.mail_max},
  format: {with: VALID_EMAIL_REGEX},
  uniqueness: true
  validates :password, presence: true,
            length: {minimum: Settings.validates.length.password_min},
            allow_nil: true
  has_secure_password
  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    @remember_token = User.new_token
    update_attribute :remember_digest, User.digest(@remember_token)
  end

  def authenticated? remember_token
    return false if remember_digest.blank?

    BCrypt::Password.new(remember_digest)
                    .is_password?(remember_token)
  end

  def forget
    update_attribute :remember_digest, nil
  end

  private
  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Pagy::Backend
  include SessionsHelper
  before_action :set_locale

  private
  def set_locale
    locale = params[:locale].to_s.strip.to_sym
    I18n.locale =
      I18n.available_locales.include?(locale) ? locale : I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase

    if user&.authenticate params[:session][:password]
      accept_user user
    else
      flash.now[:danger] = t ".invalid_user"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end

  def accept_user user
    log_in user
    params[:session][:remember_me] == "1" ? remember(user) : forget(user)
    redirect_back_or user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def about; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: %i(new show create)
  before_action :correct_user, only: %i(edit update)
  before_action :admin_user, only: %i(destroy)
  before_action :user_existence, except: %i(index new create)

  def index
    @pagy, @users = pagy User.all
  end

  def show
    return if @user

    flash[:danger] = t ".user_not_found"
    redirect_to help_url
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "success"
      redirect_to @user
    else
      flash.now[:danger] = t "fail_to_create"
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t ".profile_updated"
      redirect_to @user
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = t ".user_deleted"
    else
      flash[:danger] = t ".fail_to_delete"
    end
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = t ".please_log_in"
    redirect_to login_url
  end

  def correct_user
    @user = User.find_by id: params[:id]
    redirect_to root_url unless current_user? @user
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def user_existence
    @user = User.find_by id: params[:id]
    return if @user.present?

    store_location
    flash[:danger] = t ".user_not_found"
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  def full_title page_title
    base_title = t "title"
    page_title.blank? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user&.authenticated? :remember, cookies[:remember_token]
        log_in user
        @current_user = user
      end
    end
  end

  def current_user? user
    user && user == current_user
  end

  def logged_in?
    current_user.present?
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget user
    user.forget
    cookies.delete :user_id
    cookies.delete :remember_token
  end

  def log_out
    forget current_user
    session.delete :user_id
    @current_user = nil
  end

  def redirect_back_or default
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.gravatar.size.default
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "#{Settings.gravatar.base_url}/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.email, class: "gravatar"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to t("ruby_on_rails_tutorial"), Settings.outside_href.rails_tutorial %>
    <%= link_to t(".author"), Settings.outside_href.michael_harlt %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".about"), about_path %>
      <li><%= link_to t(".contact"), contact_path %>
      <li><%= link_to t(".news"), Settings.outside_href.rails_tutorial %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t(".home"), root_path %></li>
          <li><%= link_to t(".help"), help_path %></li>
          <% if logged_in? %>
            <li><%= link_to t(".users"), users_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t(".account")%><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t(".profile"), current_user %></li>
                <li><%= link_to t(".settings"), edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to t(".log_out"), logout_path, method: :delete %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to t("log_in"), login_path %></li>
          <% end %>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
   <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <title><%= full_title yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".form_des" %> <%= pluralize @user.errors.count, t(".foul") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".name" %></h1>
<p>
  <%= link_to t("ruby_on_rails_tutorial"), Settings.outside_href.rails_tutorial %>
  <%= link_to t(".learn_enough"), Settings.outside_href.learn_enough %>
  <%= link_to t(".book_link"), Settings.outside_href.rails_tutorial_book %>,
  <%= link_to t(".screencast"), Settings.outside_href.rails_tutorial_screencasts %>
  <%= t ".des1" %>
  <%= link_to t("ruby_on_rails"), Settings.outside_href.ruby_on_rails %>
  <%= t ".des2" %>
</p>

app/views/static_pages/contact.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".name" %></h1>
<p>
  <%= t ".des" %>
  <%= link_to t(".page"),Settings.outside_href.rails_tutorial_contact %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".name" %></h1>
<p>
  <%= t ".des" %>
  <%= link_to t("ruby_on_rails_tutorial"), Settings.outside_href.rails_tutorial_book %>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><%= t ".welcome" %></h1>

  <h2>
    <%= t ".description1_1" %>
    <%= link_to t("ruby_on_rails"),Settings.outside_href.rails_tutorial %>
    <%= t ".description1_2"  %>
  </h2>
  <%= link_to t(".sign_up_now") , signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.svg"),Settings.outside_href.ruby_on_rails %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages" %>
  <%= f.label :name, t(".name") %>
  <%= f.text_field :name %>
  <%= f.label :email, t(".email") %>
  <%= f.email_field :email %>
  <%= f.label :password, t(".password") %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation, t(".confirm") %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.gravatar.size.index %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to t(".delete"), user, data: {turbo_method: :delete, turbo_confirm: t(".you_sure")} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".save") %>
<h1><%= t ".title_name" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t(".change"), Settings.gravatar.email_url, target: "_blank" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".all_users") %>
<h1><%= t ".all_users" %></h1>

<ul class="users">
    <%= render @users %>
</ul>

<%== pagy_bootstrap_nav @pagy %>

app/views/users/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".sign_up_btn") %>
<h1><%= t ".page_name" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user-info">
      <h1>
        <%= gravatar_for @user, size: Settings.gravatar.size.large %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>